main_page = 'https://www.indeed.com'

username = '' # put your username here
password = '' # put your password here

job_urls = ['https://www.indeed.com/jobs?q=Python&l=United+States&remotejob=032b3046-06a3-4876-8dfd-474eb5e7ed11',
'https://www.indeed.com/jobs?q=Android&l=United+States&remotejob=032b3046-06a3-4876-8dfd-474eb5e7ed11',
'https://www.indeed.com/jobs?q=Software+Developer&l=United+States&remotejob=032b3046-06a3-4876-8dfd-474eb5e7ed11',
'https://www.indeed.com/jobs?q=Junior+Software+Developer&l=United+States&remotejob=032b3046-06a3-4876-8dfd-474eb5e7ed11'
] #job search url


questionAndAnswer = [
'pay','$70,000 - $80,000', 
'compensation','$70,000 - $80,000',
'salary','$70,000 - $80,000',
'address','', 
'state','', 
'postal','',
'zip', '',
'city','',
'linkedin','linkedin.com/in/josephdcantrell', 
'website','josephdcantrell.com and github.com/josephcantrell',
'github','github.com/josephcantrell',
'opportunity','Found this job through Indeed',
'dates and time','I have open availability',
'years of software development experience','4',
'years of c# experience','2',
'security clearance','None',
'gpa','3.0 Exactly',
'years of complex systems experience','0',
'years of full stack web development environment experience','0',
'years of data warehouse experience','0',
'years of golang experience','0',
'years of ruby experience','0',
'years of etl experience','0',
'years of sas experience','0',
'years of ngs or cancer genetics experience','0',
'years of api engineering experience','0',
'years of in depth sql experience','0',
'years of networking experience','0',
'years of springboot experience','0',
'years of web services experience','0',
'years of django/flask experience','0',
'years of python programming experience','2',
'years of python and qml experience','0',
'years of startup experience','0',
'years of typescript experience','0',
'years of tensorflow experience','0',
'years of terraform experience','0',
'years of zenoss experience ','0',
'years of professional experience experience ','0',
'years of python developmen experience ','2',
'years of business analysis experience ','0',
'years of ssrs experience ','0',
'years of web scraping experience ','1',
'years of databases experience ','0',
'years of mobx experience ','0',
'years of eks experience ','0',
'years of enterprise software experience ','0',
'years of html/javascript/node experience ','1',
'years of serverless/api//web/saas experience ','1',
'when will you be available to start this job','ASAP',
'years of professional ml and data eng. on large scale datasets experience ','0',
'years of mysql or oracle or mongodb experience ','1',
'years of python or ruby or php. experience ','2',
'years of overall it experience ','6',
'years of professional software development experience ','0',
'if selected for this role, what would be your earliest available start date','Now',
'years of web components experience ','0',
'years of grpc experience ','0',
'years of react native experience ','0',
'years of python development and architecture experience ','1',
'years of unit testing experience ','1',
'years of python django framework experience ','0',
'years of work experience ','6',
'years of total work experience ','6',
'who referred you to this position','None',
'years of java or python experience ','2',
'years of automating test scenarios experience ','0',
'years of automation engineering - not just testing experience ','0',
'years of analytics experience ','0',
'years of software developer experience ','6',
'tell us a bit about yourself and your experience: ','I am a recent college graduate. I really enjoy python automation and this is actually how this application is reaching you. I created an assistant to help me find and apply to jobs on Indeed and Linkedin.',
'years of php experience ','0',
'do you prefer to work independently or as part of a team','Varies. I love to work independently, but if needed I am perfectly fine working with a team.',
'how long have you been doing programming-related work','Work specifically none, I have been programming for over 6 years through Highschool, College, Freelance work, and personal experience',
'please list any programming-related projects you’ve worked on in the last 5 years (if none, please put none) ','Too many to list, First is this assistant, Linkedin assistant, Python automation bots for games',
'what’s your preferred programming platformwindows, linux, mac, other','Windows',
'are you able to work with minimal specifications and comfortable reaching out to others for the information you need','Yes',
'years of c#, .net, asp.net core experience ','2',
'years of react, typescript, javascript experience ','0',
'years of rest api design & implementations experience ','0',
'why are you a software developer','I got into software developing in Highschool when my school started a VEX robotics team. They did not have anyone that knew how to program, so I took that as a reason to learn and I have loved it ever since',
'years of raspberry pi experience ','2',
'years of json experience ','1',
'years of swagger experience ','0',
'years of aws or azure working experience ','0',
'years of oracle experience ','0',
'years of tableau experience ','0',
'years of aws cloud engineering experience ','0',
'years of lms experience ','0',
'years of cornerstone experience ','0',
'how did you hear about this role','Indeed',
'years of hl7 development experience ','0',
'years of overall development experience ','6',
'years of perl experience ','0',
'years of unix, linux experience ','1',
'years of pharmacy developer experience ','0',
'years of javascript patterns, es6, html/css, vue.js, react, angular experience ','1',
'years of php, mysql, node and python experience ','2',
'years of health information management experience ','0',
'years of mirth connect experience ','0',
'college/university ','University of Arkansas',
'years of embedded software experience ','1',
'years of programming experience ','6',
'what are your pronouns','He/Him',
'years of servicenow experience ','0',
'applicant signature ','Joseph Cantrell',
'are you proficient in fundamental front end languages such as html, css and javascript','No',
'years of experience do you have in full stack engineering','1',
'do you have a degree in computer science','Yes. B.A.',
'years of full stack engineering experience ','1',
'years of data analyst experience ','0',
'years of aws suite experience ','0',
'years of ui design & implementation experience ','1',
'share your gender pronou','He/Him',
'years of data analysis skills experience ','0',
'years of front end development experience ','1',
'who referred you to this position','None',
'years of python and lambda experience ','0',
'years of object oriented design (ood) and analysis experience ','1',
'years of robotics or a.i. industry experience ','1',
'do you have experience working with integration platformwhich one','0',
'years of data enginer experience ','1',
'years of power automate experience ','0',
'please provide your start date timeframe. ','Anytime',
'please provide your hourly rate requirements. ','30-35',
'do you have knowledge of government contracting; preferred analytics and/or solutions ','0',
'on a scale from 1 - 10 (1 being no experience, 10 being expert), how would you self rate your experience in python','7',
'years of bigdata experience ','0',
'years of data engineer experience ','1',
'how did you hear about the job','Indeed',
'please enter the amount ($','$70,000- $80,000',
'do you want to tell us anything else about you','I live in a tiny house on wheels. I converted a school bus into an RV with no outside help. Everything that has been done on this house has been by my own hands. This shows that I am capable of doing whatever is needed for me to get the job done',
'date available ','Now',
'do you have reliable internet at home','Yes',
'years of database administration experience ','1',
'years of cloudops experience ','0',
'years of automation heavily with aws environment experience ','0',
'years of shell scripting experience ','1',
'years of python hands-on coding experience ','2',
'years of hadoop administration experience ','0',
'years of 24×7 high-availability production environment experience ','0',
'years of switching experience ','0',
'years of routing experience ','0',
'years of devops engineer experience ','0',
'years of information technology experience ','6',
'years of cloud development experience ','0',
'years of site reliability engineer experience ','0',
'years of computer vision experience ','0',
'years of technical support experience ','0',
'years of data analysis & info reporting to healthcare claims data experience ','0',
'years of crm software (jira, salesforce, zendesk) experience ','0',
'years of scripting languages, bash, python etc. experience ','2',
'years of orchestration tools like kubernetes, swarm experience ','0',
'years of synthesizable c, vhdl / verilog experience ','0',
'years of sat, atpg, or reverse engineering tools experience ','0',
'years of fedramp experience ','0',
'years of teaching experience ','0',
'tell us about your experience with integrations and managing distributed teams','0',
'years of sdks experience ','1',
'years of cloud architecture experience ','0',
'years of image recognition, segmentation, classification experience ','0',
'years of data management experience ','1',
'years of ic layout experience ','0',
'how did you hear about the position','Indeed',
'years of web design experience ','1',
'years of systems engineering background experience ','0',
'years of data analysis & data science experience ','0',
'how soon are you available to start work','Now',
'do you currently have any licenses or certifications that you would like us to be aware ofplease list: ','None',
'what is your desired start date (i.e. two weeks notice)','Now',
'years of redshift experience ','0',
'years of data platform engineering experience ','0',
'years of kafka or nifi experience ','0',
'we respect chosen pronouns, please share yours','He/Him',
'what is your availability\notice period','Open Availability',
'do you have strong english language fluency and communication skills','Yes',
'years of hadoop experience ','0',
'how did you hear about the rolewhat made you apply for this position','Indeed',
'years of data mining experience ','0',
'years of team leading experience ','0',
'how did you hear about 6rs','0',
'years of microsoft sql server, administration and performance tuning experience ','0',
'years of database administration backup and recovery experience ','0',
'years of data analysis or related experience ','0',
'tell us about your experience using excel and/or google sheets ','I took a college course over excel and I used it constantly in college. I am very familiar with the software',
'recent employer ','American Estates',
'years of clinical research data collection experience ','0',
'years of clinical research management experience ','0',
'years of accounting systems experience ','0',
'years of ss&c advent geneva platform experience ','0',
'years of geneva ui experience ','0',
'in 150 characters or fewer, tell us what makes you unique. try to be creative and say something that will catch our eye!','I live in a tiny house on wheels. I converted a school bus into an RV with no outside help. Everything that has been done on this house has been by my own hands. This shows that I am capable of doing whatever is needed for me to get the job done',
'years of industrial engineering experience ','0',
'years of digital marketing experience ','0',
'years of marketing experience ','0',
'years of enhanced packet core experience ','0',
'years of content / product marketing experience ','0',
'years of windchill development experience ','0',
'years of etl pipelines experience ','0',
'years of gui experience ','1',
'years of native ui experience ','0',
'years of front end engineer experience ','1',
'years of javascript framework (vue.js, angular, react) experience ','0',
'years of cyber kill chain experience ','0',
'years of adversary tactics, techniques and procedures (ttps) experience ','0',
'years of scripting/programming experience ','6',
'years of ci/cd tools experience ','0',
'one a scale from 1 - 10 (1 being no experience, 10 being expert), how would you self rate your experience in python','7',
'years of soc experience ','0',
'link to online portfoli','github.com/josephcantrell/',
'years of microsoft sql server experience ','0',
'years of devsecops engineer experience ','0',
'years of python with pandas experience ','2',
'years of data visualization libraries experience ','0',
'years of azure data lake experience ','0',
'years of in a data engineering role using python, pyspark, scala. experience ','0',
'years of programming and analytical experience using sql. experience ','1',
'years of automation tools experience ','1',
'years of data modeling (conceptual, logical and physical) experience ','0',
'years of etl/elt experience ','0',
'years of hands on aws experience ','0',
'years of hands on docker/container experience ','1',
'years of web application experience ','0',
'years of agile development process experience ','0',
'years of front-end developer experience ','1',
'years of working in an agile scrum based dev team experience ','0',
'years of aws devops experience ','0',
'years of systems administration experience ','0',
'years of computer networking experience ','0',
'years of information security experience ','0',
'years of splunk experience ','0',
'years of spark experience ','0',
'years of ssis and/or powershell experience ','0',
'years of information retrieval experience ','0',
'describe your experience with ruby on rails or apis. ','0',
'do you have an bs or ms in computer science','No. B.A.',
'years of fortran experience ','0',
'years of bash experience ','1',
'years of blockchain experience ','0',
'years of software deployment experience ','6',
'years of technical lead or architect experience ','0',
'years of linux (redhat / rhel) experience ','0',
'do you have experience working with windbg or ollydbg','0',
'years of qtp (quick test pro), win runner, and/or hp uft experience ','0',
'have you ever used any coinbase products','No',
'years of bioinformatics experience ','0',
'years of powershell experience ','0',
'which public cloud do you have the most experience with','GCP',
'years of physical design engineering experience ','0',
'years of block-level and full-chip integration experience ','0',
'years of life insurance or life reinsurance experience ','0',
'years of life pricing experience ','0',
'years of quantitative analysis experience ','0',
'years of business consulting experience ','0',
'years of cpq experience ','0',
'years of sap experience ','0',
'years of rtl design and verification experience ','0',
'years of system-on-chip design verification experience ','0',
'years of data modeler experience ','0',
'years of secondary mortgage markets experience ','0',
'years of client-side web development experience ','0',
'were you referred by someoneif so, whom','None',
'years of amazon web services (aws) experience ','0',
'years of it implementation experience experience ','1',
'years of mobile app development experience ','1',
'years of e-commerce/e-finance experience ','0',
'years of native android 3d graphics experience ','1',
'years of arcore experience ','0',
'years of android development experience ','1',
'years of image processing experience ','0',
'years of mobile development experience ','1',
'years of library/ archive experience ','0',
'years of webrtc experience ','0',
'years of media playback libraries on android experience ','0',
'years of as a paid professional software developer experience ','0',
'years of as a paid, professional front-end/ui/ux designer/developer experience ','0',
'years of mobile apps for android, ios, and web. experience ','1',
'years of reactive programming – rx swift experience ','0',
'years of designing and developing scalable features experience ','0',
'years of google play store experience ','1',
'years of android developer experience ','1',
'years of invision experience ','0',
'years of xamarin.forms experience ','0',
'years of computer graphics experience ','0',
'years of ui/ux experience ','1',
'years of objective-c experience ','1',
'years of product design experience ','0',
'years of native experience ','0',
'years of lead exp experience ','0',
'years of mobile devices experience ','1',
'years of appdev experience (java or c# preferred) experience ','1',
'years of appsec as and analyst or engineer experience ','0',
'years of management experience ','0',
'years of pos experience ','3',
'years of sales experience ','3',
'years of social media experience ','0',
'years of media ad buying experience ','0',
'years of product management experience ','0',
'years of digital (mobile/web applications) product experience ','1',
'years of writing skills experience ','4',
'what is your hourly rate (in usd)','30-35',
'what is your native speaking language','English',
'years of customer service experience ','3',
'years of microsoft office experience ','4',
'years of project management or analyst experience ','0',
'years of detailing experience ','0',
'years of api testing (postman) experience ','1',
'years of system analyst experience ','0',
'years of mobile application development experience ','1',
'years of database design experience ','1',
'years of rpa experience ','0',
'years of vicidial php experience ','0',
'years of complex healthcare information systems (it) experience ','0',
'years of apis experience ','1',
'years of ajax experience ','0',
'years of spring experience ','0',
'years of zoho crm experience ','0',
'years of web developer experience experience ','1',
'years of professional java development experience ','0',
'approximately how many projects (of years, if too many projects) have you coded in react','0',
'years of microsoft windows server experience ','0',
'years of middleware experience ','0',
'years of back-end web development experience ','1',
'years of responsive grid frameworks (e.g. bootstrap, foundations experience ','0',
'years of front-end web development experience ','1',
'years of strong sql experience do you have','0',
'years of as a paid professional software developer experience do you have','0',
'years of as a paid, professional front-end/ui/ux designer/developer experience do you have','0',
'years of microsoft sql server experience do you have','0',
'years of programming experience do you have','6',
'years of aws or azure working experience do you have','0',
'years of rest api design experience do you have','0',
'years of spring mvc experience do you have','0',
'years of scala experience do you have','0',
'years of aws development experience do you have','0',
'years of java enterprise edition 8 experience do you have','0',
'describe your experience in ruby or another object oriented language','0',
'years of drupal experience do you have','0',
'years of cloud environments such as aws, azure, or gcp experience do you have','0',
'years of oracle, ms sql server, mongo db, or redis, etc experience do you have','0',
'years of java for application development experience do you have','1',
'years of html/javascript/node experience do you have','1',
'years of serverless/api//web/saas experience do you have','0',
'do you speak english - fluently (must be fluent)','Yes',
'years of react native experience do you have','0',
'years of drupal layout builder experience do you have','0',
'years of ui development experience do you have','1',
'years of javascript or typescript experience do you have','0',
'years of php experience do you have','0',
'years of jquery experience do you have','0',
'years of medical industry experience do you have','0',
'years of running nginx & apache web servers experience do you have','0',
'years of mobile development experience do you have','1',
'years of library/ archive experience do you have','0',
'years of apis experience do you have','1',
'years of software experience do you have','6',
'years of insurance experience do you have','0',
'years of rails experience do you have','0',
'years of image processing experience do you have','0',
'years of embedded software experience do you have','1',
'years of a jira administering experience do you have','0',
'years of developing web api to create restful web services experience do you have','0',
'years of js react experience do you have','0',
'years of of data formats such as xml, csv and json experience do you have','1',
'for this job, are you able to commute or relocate to arlington, tx 76011','No',
'years of vue experience do you have','0',
'years of netsuite experience do you have','0',
'years of supply chain management experience do you have','0',
'years of identity & access management experience do you have','0',
'years of dba experience do you have','0',
'years of oracle experience do you have','0',
'years of databases experience do you have','0',
'years of service now integration experience do you have','0',
'years of developing large scale distributed systems experience do you have','0',
'years of object oriented programming experience do you have','3',
'years of c#/.net experience do you have','2',
'years of entity framework experience do you have','0',
'years of developer experience do you have','6',
'years of hands on developing java applications experience do you have','0',
'years of working with jee or spring frameworks experience do you have','0',
'years of working with saas application experience do you have','0',
'years of java, angular and aws experience do you have','1',
'years of front-end using angular 2.0, angularjs experience do you have','0',
'years of front-end using html/javascript and npm experience do you have','0',
'years of database skills: oracle, postgres experience do you have','0',
'years of cybersecurity experience do you have','0',
'years of laravel/vue experience do you have','0',
'years of javascript/java experience do you have','1',
'years of objective-c experience do you have','1',
'years of visual studio experience do you have','2',
'years of field service edge experience do you have','0',
'years of ibm maximo experience do you have','0',
'years of regex experience do you have','0',
'years of json experience do you have','2',
'years of enterprise software experience do you have','0',
'years of microservices experience do you have','0',
'years of rest api experience do you have','1',
'years of javascript (se6) experience do you have','1',
'years of javascript patterns, es6, html/css, vue.js, react, angular experience do you have','1',
'years of php, mysql, node and python experience do you have','2',
'years of git, jirl and confluence experience do you have','0',
'years of web design experience do you have','1',
'years of network security experience','0',
'years of rhel linux administration experience','0',
'years of teaching coding experience','1',
'years of ios development experience','0',
'years of apache big data frameworks (hadoop, spark, hive) experience','0',
'years of docker and kubernetes experience','0',
'years of workflow scheduling/orchestration tools (oozie, jenkins) experience','0',
'years of reporting and analytics experience','0',
'years of java/python experience','2',
'years of data modeling experience','0',
'years of data warehouse experience','0',
'years of python or other relevant experience','2',
'years of openstack cloud experience','0',
'years of linux system administrator experience','0',
'years of python/powershell experience','2',
'years of windows administration experience','0',
'years of configuration management or dsc experience','0',
'years of c++ or c# experience','2',
'years of docker experience','1',
'years of api integration experience','0',
'years of open stack experience','0',
'years of jira or bugzilla and (bash or python or perl) experience','0',
'years of bioinformatics and software and development experience','0',
'years of usaco experience','0',
'years of c/c++ experience','1',
'years of aws and/or gcp experience','0',
'years of power bi experience','0',
'years of aws/azure experience','0',
'years of atlassian experience','0',
'years of aws (s3, ec2, emr, sqs, sns, lambda, rds, iam) experience','0',
'years of spark with scala experience','0',
'years of big data engineer experience','0',
'how did you hear about this job','Through Indeed.com',
'years of data or algorithm scientist with imaging applications experience','0',
'years of cypress/jess experience','0',
'years of etl and datawarehousing experience','0',
'years of airflow and jira experience','0',
'years of gcp and ssis to bigquery sql experience','0',
'years of it experience','6',
'years of ui experience','1',
'years of networking automation experience','0',
'years of linux/unix experience','1',
'years of linux experience','1',
'years of api experience','1',
'years of minecraft experience','4',
'years of block-based coding experience','1',
'years of lua experience','0',
'years of roblox experience','6',
'years of shiny experience','0',
'years of r experience','0',
'years of iics experience','0',
'years of big query experience','0',
'years of pandas experience','0',
'years of hp alm experience','0',
'years of heroku experience','1',
'years of iot experience','1',
'years of ansible experience','0',
'years of ibm api connect experience','0',
'years of apigee experience','0',
'years of software development/engineering experience','4',
'years of reactjs experience','0',
'years of multi-threading implementations in python experience','0',
'years of building highly performant rest api’s with oauth experience','0',
'years of deploying saas application using cloud native technologies experience','0',
'years of enterprise-level applications, startups or consulting experience','0',
'years of application development and design experience','2',
'years of kubernetes, microservices experience','0',
'years of team lead experience','0',
'years of node, go, python 3 experience','2',
'years of test automation experience','1',
'years of selenium experience','1',
'years of talend experience','0',
'years of do178 or do254 experience','0',
'years of c and python experience','3',
'years of visual studio, android studio experience','2',
'years of .net core, nodejs, react, c#, api dev experience','0',
'years of mysql with strong sql and store procedure experience','0',
'years of sql scripting experience','0',
'years of azure data factory experience','0',
'years of drive ci/cd best practices experience','0',
'years of devops principles experience','0',
'years of sre or devops engineer experience','0',
'years of system administration experience','0',
'years of cloud infrastructure experience','0',
'years of ci/cd experience','0',
'years of api experience','0',
'years of ansible experience','0',
'years of relevant experience','0',
'years of fixed income securities or bonds experience','0',
'years of java development experience','1',
'years of hl7 experience','0',
'years of fhir api experience','0',
'years of c#, python, ruby, java experience','5',
'years of data base technology experience','0',
'years of do178 or do254 experience','0',
'years of c and python experience','3',
'years of programming in c,c++ or rust experience','1',
'us citizen','Yes',
'years of angular js or react experience','0',
'years of full stack experience','1',
'years of ssis experience','0',
'years of go experience','0',
'years of c experience','1',
'years of agile experience','0',
'years of aws cloud experience','0',
'years of c++ experience','1',
'years of devops experience','0',
'years of java experience','1',
'years of ci/cd experience','0',
'years of java/python experience','3',
'years of python or java script experience','3',
'years of rest experience','1',
'spring framework experience','0',
'years of javascript experience','1',
'years of html experience','1',
'years of html5 experience','1',
'years of postgres experience','0',
'years of lambdas, s3 or dms experience','0',
'years of lambdas experience','0',
'years of s3 experience','0',
'years of dms experience','',
'years of restful experience','1',
'years of mobile applications experience','1',
'years of full-stack software development experience','1',
'years of lamp stack experience','0',
'years of azure experience','0',
'years of mysql experience','1',
'years of angular 1 experience','0',
'years of django experience','0',
'years of erp/sap experience','0',
'years of .net experience','0',
'years of css experience','1',
'years of swift experience','0',
'years of Mac OS experience','0',
'years of vue.js experience','0',
'years of laravel experience','0',
'years of vue.js or laravel experience','0',
'years of sql (or similar) experience','1',
'years of complex systems experience','0',
'legal name','Joseph Cantrell',
'Full name','Joseph Cantrell',
'name','Joseph Cantrell',
'years of full stack web development environment experience','0',
'years of agile experience','0',
'years of scrum experience','0',
'years of test framework engineering experience','0',
'years of kubernetes experience','0',
'years of people/project management experience','0',
'years of senior dev experience','0',
'years of aws & gcp experience','1',
'years of oracle database development experience','0',
'years of software engineering experience','6',
'years of building back-end apis and databases experience','0',
'years of reporting and analytics experience','0',
'years of clinical research experience','0',
'years of coding experience','6',
'years of data science experience','0',
'years of react js experience','0',
'years of aws cloud platforms experience','0',
'years of react/preact javascript experience','0',
'years of cisco experience','0',
'years of material-ui experience','0',
'years of django python experience','2',
'years of html, css experience','1',
'years of computer science experience','6',
'years of machine learning experience','0',
'years of sdet experience','0',
'years of frontend development experience','1',
'years of data engineering experience','0',
'years of php experience experience','0',
'years of emr/ehr and hl7 experience','0',
'years of emr experience','0',
'years of ehr experience','0',
'years of h17 experience','0',
'years of react experience','0',
'years of backend development experience','1',
'years of unreal engine experience','0',
'years of c++ programming experience','1',
'years of angular experience','0',
'years of front-end development experience','1',
'years of google analytics experience','0',
'years of full stack development experience','1',
'years of hands-on java development experience','1',
'years of experience do you have working with python','2',
'years of experience do you have working with django?','0',
'have you ever used python or django in a professional environment','no',
'ears of database development experience','1',
'git, maven, gradle, ant','0',
'years of git experience','1',
'years of gradle experience','0',
'years of ant experience','0',
'years of maven experience','0',
'years of junit/mockito experience','0',
'years of junit experience','0',
'years of mockito experience','0',
'years of three.js experience','0',
'years of 3d graphics and/or three.js experience','0',
'years of software engineering (java) experience','1',
'years of 3d graphics experience','0',
'years of sql server management studio experience','0',
'years of database development experience','1',
'years of ruby on rails experience','0',
'years of react/redux experience','0',
'years of node.js experience','0',
'years of programming languages','6',
'years of magento experience','0',
'years of python development experience','2',
'years of pyspark experience','0',
'years of ms access experience','0',
'years of project management experience','0',
'years of mongodb experience','0',
'years of back-end development experience','1',
'years of enterprise development experience','0',
'years of restful webservices experience','1',
'years of building production software experience','0',
'years of delivering ios and android mobile applications experience','0',
'years of wordpress experience','0',
'years of c#/asp.net experience','2',
'years of mirth experience','0',
'years of python experience','2',
'years of leadership experience','1',
'years of GraphQL experience','0',
'years of drupal development experience','0',
'years of test-driven development experience','0',
'years of desktop applications experience','2',
'years of kotlin experience','0',
'years of android experience','1',
'years of building/scaling backend servers experience','0',
'years of web development experience','1',
'years of postgresql experience','0',
'years of aws experience','0',
'years of amazon web services experience','0',
'years of GCP experience','0',
'years of Google Cloud experience','0',
'years of Google Cloud Platform experience','0',
'years of ASP.NET experience','0',
'years of Development experience','4',
'years of sql experience','1',
'years of grails experience','0',
'years of groovy experience','0',
'years of flutter experience','0',
'Job title','Freelance Software Developer',
'Company','Personal',
'work authorization','US Citizen',
'phone number','',
'mobile number','',
'phone','',
'sponsorship','No'
]
